#branches:
#    except:
os:
    - linux
    - osx
dist: trusty
sudo: false
language: c
compiler:
    - gcc
#
before_install:
install:
before_script:
script:
    - make
    - make test
#deploy:
#  provider: releases
#  skip_cleanup: true
#  on:
#    tags: true
notifications:
    email: false
