#branches:
#    except:
os:
    - linux
    - osx
dist: trusty
sudo: false
language: c
compiler:
    - gcc
    - clang

before_install:
install:
before_script:
script:
    - make
    - make test
    - make run
    - gcov src/xusto.c
after_success:
    - bash <(curl -s https://codecov.io/bash)

#deploy:
#  provider: releases
#  skip_cleanup: true
#  on:
#    tags: true
notifications:
    email: false
