# .travis.yml

os:
    - linux
    - osx
dist: trusty
sudo: false
language: c
compiler:
    - gcc
    - clang

before_install:
install:
before_script:
script:
    - make
    - make test
    - make run-integration
after_success:
    # Upload coverage reports
    - bash <(curl -s https://codecov.io/bash)
    - make clean

notifications:
    email: false
