#branches:
#    except:
os:
    - linux
    - osx
dist: trusty
sudo: false
language: c
compiler:
    - gcc
    - clang
#
before_install:
install:
before_script:
script:
    #- rvm get stable # https://github.com/travis-ci/travis-ci/issues/6307
    - make
    - make test
    - make run
#deploy:
#  provider: releases
#  skip_cleanup: true
#  on:
#    tags: true
notifications:
    email: false
